export default {
  dom: 'body',
  debugLevel: 1,
  selectedFont: 'sans-serif',
  expandToolbar: true,
  enableToolbar: true,
  rootClass: 'hocr-viewer',
  scaleFactor: 1,
  fonts: {
    'sans-serif': {},
    serif: {},
    monospace: {},
    UnifrakturCook: {cssUrl: 'https://fonts.googleapis.com/css?family=UnifrakturCook:700'},
    UnifrakturMaguntia: {cssUrl: 'https://fonts.googleapis.com/css?family=UnifrakturMaguntia'},
    'Old Standard TT': {cssUrl: 'https://fonts.googleapis.com/css?family=Old+Standard+TT'},
    Cardo: {cssUrl: 'https://fonts.googleapis.com/css?family=Cardo'},
    'Noto Serif': {cssUrl: 'https://fonts.googleapis.com/css?family=Noto+Serif:400,400i,700&subset=latin-ext'},
    'Libre Baskerville': {cssUrl: 'https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i,700&subset=latin-ext'},
  },
  features: {
    layout: {enabled: true},
    backgroundImage: {enabled: false},
    scaleFont: {
      enabled: false,
      maxFontSize: 128,
      minFontSize: 2,
      wrapClass: 'hocr-viewer-wrap',
    },
    disableEmStrong: {enabled: false},
    contentEditable: {enabled: false},
    tooltips: {
      enabled: true,
      styleId: 'hocr-viewer-tooltip-style',
    },
    transparentText: {enabled: false},
    highlight: {enabled: true},
    highlightNotPage: {enabled: false},
    highlightInline:  {enabled: false},
    highlightLine:    {enabled: false},
    highlightPar:     {enabled: false},
    highlightCarea:   {enabled: false},
  },
}
